# Use postgres/example user/password credentials
version: "3.1"

services:
  db:
    container_name: postgres_db
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: sandbox
      POSTGRES_USER: sandbox
      POSTGRES_PASSWORD: sandbox

  redis:
    container_name: gobarber_redis
    image: 'bitnami/redis:latest'
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  mongo:
    container_name: gobarber_mongo
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: sandbox
    #   MONGO_INITDB_ROOT_PASSWORD: sandbox

  mongo-express:
    container_name: gobarber_mongo_express
    image: mongo-express
    restart: always
    ports:
      - 8989:8081
    # environment:
    #   ME_CONFIG_MONGODB_ADMINUSERNAME: sandbox
    #   ME_CONFIG_MONGODB_ADMINPASSWORD: sandbox
