# Use postgres/example user/password credentials
version: "3.1"

services:
  db:
    image: postgres
    restart: always
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: sandbox
      POSTGRES_USER: sandbox
      POSTGRES_PASSWORD: sandbox

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: sandbox
      MONGO_INITDB_ROOT_PASSWORD: sandbox

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8989:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: sandbox
      ME_CONFIG_MONGODB_ADMINPASSWORD: sandbox
